### ISSUE TITLE
suggestionContainerStyle is used twice but never defined

### ISSUE THREAD

**Issue by makoto** [status-im/docs.status.im#13]
https://github.com/status-im/docs.status.im/search?utf8=%E2%9C%93&q=suggestionContainerStyle&type=

`suggestionContainerStyle`  is used in two of the docs but never defined.

```
status.components.view(
                suggestionContainerStyle,
                [status.components.view(
                    suggestionSubContainerStyle,
                    [
                        status.components.text(
                            {style: valueStyle},
                            entry
                        )
                    ]
                )]
            )
```

Replacing `suggestionSubContainerStyle` with `{}` will now raise the following error and crashes the app when you press either `Hello` or `Goodbye`

```
05-30 10:09:06.180 12745 12865 E ReactNativeJS: No protocol method IAssociative.-assoc defined for type string: Hello
```

Please be aware that there is a very similar `suggestionsContainerStyle(suggestionsCount)` function but that's used at a different location.

```
    var view = status.components.scrollView(
        suggestionsContainerStyle(2),
        suggestions
    );
```

**Comment by andytudhope** [comment]
Closing to clean repo for complete overhaul, thanks for reporting though.
