### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by pablanopete** [status-im/docs.status.im#54]
Technikon needs contribution guidelines so users who come into the fold can understand what is needed / the purpose as well as the best place to get started if you want to add to existing documentation. As well as what kind of pages wouldn't be accepted. 

EG: wikipedia contribution purpose - getting started etc. https://en.wikipedia.org/wiki/Wikipedia:Contributing_to_Wikipedia

**Comment by andytudhope** [comment]
Would you like to write one @pablanopete?

Each page now has an edit button which take you directly to the proper file on the right branch in github. The README in this repo has instructions on how to add more complicated things if you want to make a whole new page etc.

**Comment by andytudhope** [comment]
Solved by https://github.com/status-im/docs.status.im/commit/881294ab26d4add34734314af564ab42e87763e5
